set(_CATKIN_CURRENT_PACKAGE "imu_ah100b")
set(imu_ah100b_VERSION "0.0.0")
set(imu_ah100b_MAINTAINER "xiqin <xiqin@todo.todo>")
set(imu_ah100b_PACKAGE_FORMAT "2")
set(imu_ah100b_BUILD_DEPENDS "roscpp" "sensor_msg" "serial" "std_msgs" "sensor_msgs")
set(imu_ah100b_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msg" "serial" "std_msgs" "sensor_msgs")
set(imu_ah100b_BUILDTOOL_DEPENDS "catkin")
set(imu_ah100b_BUILDTOOL_EXPORT_DEPENDS )
set(imu_ah100b_EXEC_DEPENDS "roscpp" "sensor_msg" "serial" "std_msgs" "sensor_msgs")
set(imu_ah100b_RUN_DEPENDS "roscpp" "sensor_msg" "serial" "std_msgs" "sensor_msgs")
set(imu_ah100b_TEST_DEPENDS )
set(imu_ah100b_DOC_DEPENDS )
set(imu_ah100b_URL_WEBSITE "")
set(imu_ah100b_URL_BUGTRACKER "")
set(imu_ah100b_URL_REPOSITORY "")
set(imu_ah100b_DEPRECATED "")